- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present     

- name: Install Docker packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin

- name: Install docker-compose        
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Make sure /etc/docker dir exists
  file:
    path: /etc/docker
    state: directory

- name: Edit docker configs
  copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "200m",
        "max-file": "3"
        }
      }
    dest: /etc/docker/daemon.json
  notify:
    - restart docker 
