version: '3.9'

services:
  manager:
    environment:
      - VISUALIZER_TYPE=manager
    image: yandeu/visualizer:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hc_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.visualizer.rule=Host(`who1.powerusers.ir`)"
        - "traefik.http.middlewares.visualizer-whitelist.ipwhitelist.sourcerange=5.78.43.87/32"
        - "traefik.http.routers.visualizer.middlewares=visualizer-whitelist"
        - "traefik.http.routers.visualizer.service=visualizer"
        - "traefik.http.services.visualizer.loadbalancer.server.port=3500"
        - "traefik.http.routers.visualizer.entrypoints=visualizer"
    labels:
      - visualizer.manager
  agent:
    environment:
      - VISUALIZER_TYPE=agent
    image: yandeu/visualizer:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hc_net 
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    labels:
      - visualizer.agent
networks:
  hc_net:
    external: true
